/**
 * Insert Claude Opus-generated analyses for run 864fad8b (April 17, 2026)
 * Generated by Claude Opus 4.6 based on SERP + snapshot context data.
 *
 * Usage: set -a && source .env.local && set +a && npx tsx pipeline/insert-claude-opus-analyses.ts
 */
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

const RUN_ID = '864fad8b-ee94-4ade-a4a4-4a877d9c42c1';

interface AnalysisInsert {
  run_id: string;
  keyword_id: string;
  country: string;
  device: string;
  analysis_type: 'lacoste_gap' | 'top3_deep_dive';
  content: string;
  tags: string[];
  lacoste_position: number | null;
  search_intent?: string;
  sources: { position: number; domain: string; actor_name: string; url: string }[];
  opportunity_score?: number;
}

const analyses: AnalysisInsert[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // 1. SACOCHE HOMME — FR — Lacoste #3
  // ═══════════════════════════════════════════════════════════════════════════
  {
    run_id: RUN_ID,
    keyword_id: '207100a0-5d23-432b-9977-5cb2878f5cba',
    country: 'FR',
    device: 'mobile',
    analysis_type: 'lacoste_gap',
    lacoste_position: 3,
    search_intent: 'transactional',
    opportunity_score: 6,
    tags: ['search_intent_mismatch', 'content_coverage', 'content_depth', 'structure_hn', 'meta_title', 'meta_description', 'structured_data'],
    sources: [
      { position: 1, domain: 'www.amazon.fr', actor_name: 'Amazon', url: 'https://www.amazon.fr/sacoche-homme/s?k=sacoche+homme' },
      { position: 2, domain: 'www.galerieslafayette.com', actor_name: 'Galeries Lafayette', url: 'https://www.galerieslafayette.com/c/homme/sacs-bagages/sacs/sacoches' },
      { position: 3, domain: 'www.lacoste.com', actor_name: 'Lacoste', url: 'https://www.lacoste.com/fr/lacoste/homme/sacs-petite-maroquinerie/sacoches-pochettes/' },
      { position: 4, domain: 'www.zalando.fr', actor_name: 'Zalando', url: 'https://www.zalando.fr/sacs-bandouliere-homme/' },
      { position: 5, domain: 'www.laboutiqueofficielle.com', actor_name: 'La Boutique Officielle', url: 'https://www.laboutiqueofficielle.com/sacoches-sacs-c54/homme' },
      { position: 6, domain: 'www.lancaster.com', actor_name: 'Lancaster', url: 'https://www.lancaster.com/collections/homme' },
      { position: 7, domain: 'www.cdiscount.com', actor_name: 'Cdiscount', url: 'https://www.cdiscount.com/bagages/r-sacoche+homme.html' },
      { position: 8, domain: 'www.blackstore.fr', actor_name: 'Blackstore', url: 'https://www.blackstore.fr/mode-homme/accessoires-homme/sacoches-homme/' },
      { position: 9, domain: 'fr.tommy.com', actor_name: 'Tommy Hilfiger', url: 'https://fr.tommy.com/sacs-pour-homme' },
      { position: 10, domain: 'www.decathlon.fr', actor_name: 'Decathlon', url: 'https://www.decathlon.fr/homme/sacoches-homme' },
    ],
    content: `### Alignement intention
- La requête "sacoche homme" est clairement transactionnelle — l'utilisateur recherche un produit à acheter, pas des informations éditoriales
- **Amazon** (#1) capte la position dominante grâce à un H1 contenant l'expression exacte "sacoche homme" et un catalogue de 60 000+ résultats
- **Galeries Lafayette** (#2) affiche un H1 "Sacoches homme" bien ciblé, avec navigation par marques incluant Lacoste
- **Lacoste** (#3) utilise le titre "Sacoches & pochettes pour homme | Lacoste FR" — le mot-clé "sacoche homme" est absent du H1, remplacé par un titre plus marketing
- Le snippet Lacoste est attractif ("Une collection pensée pour l'homme en quête d'un style clair") mais ne contient pas l'expression exacte de la requête
- La SERP est dominée par des pages catégorie/listing avec filtres — format PLP attendu par Google pour cette intention

### Couverture sémantique
- **Cdiscount** (#7) écrase la concurrence avec **42 occurrences** du mot-clé "sacoche homme", dont 1 en H1, accompagné d'un paragraphe éditorial de 80+ mots sous le listing produit
- **Decathlon** (#10) affiche **7 occurrences** avec le mot-clé en H1 et 2 fois en H2, et propose un texte éditorial décrivant les usages sportifs de la sacoche
- **Zalando** (#4) atteint **3 occurrences** dont 1 en H2, sans contenu éditorial significatif
- **Lacoste** (#3) ne comptabilise que **2 occurrences** totales, dont **0 dans les headings** — le mot-clé apparaît uniquement dans le corps de texte marketing mais jamais dans la structure Hn
- **Galeries Lafayette**, **La Boutique Officielle**, **Lancaster**, **Blackstore** et **Tommy Hilfiger** affichent tous **0 occurrence** du mot-clé exact, ce qui indique que Google valorise l'autorité de domaine et le maillage interne pour ces résultats
- L'écart entre Cdiscount (42) et Lacoste (2) est un signal clair d'optimisation sémantique insuffisante

### Structure
- Le format standard de la SERP est une page catégorie (PLP) avec H1 descriptif contenant le mot-clé + système de filtrage (marque, couleur, taille, prix)
- **Amazon** utilise un système de tri avancé (prix, avis, nouveautés) et des badges sponsorisés
- **Galeries Lafayette** propose une navigation par marques exhaustive (A Bathing Ape à Zippo) avec filtrage multi-critères
- **Lacoste** structure sa page par collections (The Blend, Men's Classic, Chantaco, Nomogramme, Neocroc) plutôt que par attributs de produit classiques — cette approche branding-first peut nuire à l'exploration du catalogue pour un utilisateur qui cherche simplement "sacoche homme"
- **Cdiscount** ajoute un contenu éditorial sous le H1 expliquant les types de sacoches, ce qui enrichit le signal sémantique
- **Decathlon** propose une arborescence sport/activité qui contextualise la sacoche dans un usage, renforçant la pertinence thématique

### Optimisation meta
- **La Boutique Officielle** (#5) dispose d'une meta description ciblée : "Découvrez la Nouvelle Collection de Sacoches - Sacs Homme disponible maintenant | Plus de 300 marques..."
- **Amazon** s'appuie sur des snippets auto-générés à partir des produits, incluant noms de produits et prix
- **Lacoste** a un snippet attractif mais brand-centric : "Une collection pensée pour l'homme en quête d'un style clair, actif, moderne" — pertinent pour le branding mais manque le mot-clé exact "sacoche homme"
- **Zalando** mentionne explicitement "sacoche homme revisitée" dans son snippet, captant l'attention transactionnelle
- L'optimisation du title tag avec [mot-clé principal] + [différenciateur marque] serait plus efficace que le format actuel "Sacoches & pochettes pour homme | Lacoste FR"

### Données structurées
- **Cdiscount** (#7) domine avec un balisage riche : BreadcrumbList, CollectionPage, ItemList, **Product x63**, **Offer x63**, **AggregateRating x40** — ce qui lui permet d'afficher des rich snippets avec prix et avis
- **La Boutique Officielle** (#5) implémente Product + AggregateOffer + BreadcrumbList — balisage complet pour une page catégorie
- **Decathlon** (#10) utilise Product + AggregateOffer + AggregateRating + BreadcrumbList — coverage similaire à Cdiscount
- **Tommy Hilfiger** (#9) implémente ItemList + ListItem x51 + BreadcrumbList — bonne structuration de la liste produit
- **Lacoste** (#3) ne déploie que **BreadcrumbList + ListItem x4** — pas de schema Product, pas d'Offer, pas d'avis. C'est insuffisant pour une page catégorie e-commerce et limite le potentiel de rich snippets
- **Amazon**, **Galeries Lafayette** et **Zalando** n'ont pas de données structurées observables dans les snapshots, mais bénéficient de l'autorité de domaine

## Recommandations
1. Intégrer le mot-clé exact "sacoche homme" dans le H1 de la page Lacoste (actuellement absent) — par exemple "Sacoches homme | Collection Lacoste"
2. Ajouter un bloc de contenu éditorial (80-150 mots) sous le listing produit décrivant les typologies de sacoches, matériaux et occasions d'usage, à l'image de ce que font Cdiscount et Decathlon
3. Implémenter les schemas Product + Offer + AggregateRating sur chaque produit de la page catégorie pour activer les rich snippets (prix, avis) dans la SERP
4. Renforcer la densité du mot-clé dans les sous-titres H2/H3 de la page (par exemple "Sacoches homme en cuir", "Sacoches homme en toile") au lieu des noms de collections internes
5. Optimiser le title tag avec le mot-clé en position initiale : "Sacoche Homme : Collection Cuir & Toile | Lacoste FR"
6. Ajouter des filtres par attributs classiques (matière, couleur, prix) en complément de la navigation par collections pour améliorer l'UX transactionnelle`,
  },

  {
    run_id: RUN_ID,
    keyword_id: '207100a0-5d23-432b-9977-5cb2878f5cba',
    country: 'FR',
    device: 'mobile',
    analysis_type: 'top3_deep_dive',
    lacoste_position: 3,
    tags: ['meta_title', 'content_depth', 'structure_hn', 'structured_data', 'meta_description'],
    sources: [
      { position: 1, domain: 'www.amazon.fr', actor_name: 'Amazon', url: 'https://www.amazon.fr/sacoche-homme/s?k=sacoche+homme' },
      { position: 2, domain: 'www.galerieslafayette.com', actor_name: 'Galeries Lafayette', url: 'https://www.galerieslafayette.com/c/homme/sacs-bagages/sacs/sacoches' },
      { position: 3, domain: 'www.lacoste.com', actor_name: 'Lacoste', url: 'https://www.lacoste.com/fr/lacoste/homme/sacs-petite-maroquinerie/sacoches-pochettes/' },
    ],
    content: `### Analyse des titles
- **Amazon** (#1) : H1 = "1-48 of over 60,000 results for 'sacoche homme'" — H1 technique auto-généré contenant le mot-clé exact, title tag "Sacoche Homme - Amazon.fr" simple et efficace
- **Galeries Lafayette** (#2) : H1 = "Sacoches homme" — concis, contient le mot-clé au pluriel, title tag "Sacoches homme - Galeries Lafayette" avec la marque retailer en suffixe
- **Lacoste** (#3) : H1 absent dans le contenu visible (la page commence par des bannières marketing et des liens de navigation par collection). Title tag "Sacoches & pochettes pour homme | Lacoste FR" — plus long, dilue le mot-clé avec "pochettes" et reformule "homme" en "pour homme"
- Point clé : les deux premiers résultats utilisent des H1 courts et directs contenant l'expression exacte, tandis que Lacoste privilégie un angle marketing qui affaiblit le signal SEO

### Profondeur de contenu
- **Amazon** (#1) : seulement **1 occurrence** du mot-clé (dans le H1 auto-généré). Le contenu est essentiellement constitué de listings produits avec images, prix et badges sponsorisés. Aucun contenu éditorial
- **Galeries Lafayette** (#2) : **0 occurrence** du mot-clé dans le corps de page. La page propose une navigation par marques riche (50+ marques listées dont Boss, Bottega Veneta, Calvin Klein, Lacoste) et des filtres par taille, mais aucun texte descriptif. Son classement repose sur l'autorité du domaine et la pertinence structurelle
- **Lacoste** (#3) : **2 occurrences** dans le contenu body, principalement dans le snippet marketing ("Une sacoche homme devient plus qu'un accessoire"). La page est organisée par sous-collections visuelles (The Blend, Men's Classic, Chantaco, Nomogramme, Neocroc) avec des images de catégorie — approche brand-driven mais pauvre en contenu textuel optimisé
- Aucun des trois leaders n'investit dans du contenu éditorial significatif — une opportunité pour Lacoste de se différencier avec un guide de style ou une présentation des matériaux

### Structure
- **Amazon** : structure technique de search results page avec tri (prix, avis, nouveautés), publicités intégrées, badges Amazon's Choice. Format mobile-first avec grille produit scrollable
- **Galeries Lafayette** : page catégorie classique avec breadcrumb (Homme > Sacs & Bagages > Sacs > Sacoches), navigation par marques sous le H1, puis grille produit. Filtrage par taille, marque, prix
- **Lacoste** : la page débute par des bannières d'information marketing (carte cadeau, bestsellers), puis propose des "pastilles" de navigation par collection avec images. Pas de filtres classiques (prix, couleur, matière) visibles dans le contenu scrappé. Cette structure est orientée découverte/branding plutôt que conversion rapide
- L'absence de filtres par attributs chez Lacoste est un handicap UX par rapport à Amazon et Galeries Lafayette qui permettent un parcours d'achat plus direct

### Données structurées
- **Amazon** (#1) : aucune donnée structurée détectée dans le snapshot — Amazon s'appuie sur sa reconnaissance de domaine par Google plutôt que sur le balisage schema
- **Galeries Lafayette** (#2) : aucune donnée structurée détectée — même stratégie de brand authority
- **Lacoste** (#3) : BreadcrumbList + ListItem x4 — balisage minimal de navigation. Pas de schema Product, Offer ou AggregateRating sur la page catégorie
- Aucun des trois leaders n'exploite pleinement les données structurées sur cette SERP, ce qui ouvre une fenêtre d'opportunité : l'implémentation de ItemList + Product + Offer par Lacoste pourrait créer un avantage de visibilité SERP

### Optimisation meta
- **Amazon** : meta description auto-générée à partir du contenu produit, incluant naturellement "sacoche homme" et des descriptions de produits
- **Galeries Lafayette** : snippet référençant des prix ("320,00 €", "690,00 €") et des noms de produits, générant un CTR attractif pour les acheteurs
- **Lacoste** : snippet marketing "Une collection pensée pour l'homme en quête d'un style clair, actif, moderne" — évocateur mais ne mentionne ni prix, ni nombre de produits, ni avantages concurrentiels concrets (livraison gratuite, retours, etc.)
- Recommandation : enrichir la meta description Lacoste avec des éléments transactionnels (nombre de modèles, fourchette de prix, livraison gratuite) pour améliorer le CTR

## Points clés
1. Lacoste occupe une **position #3 solide** mais son écart avec les 2 leaders est principalement structurel : absence du mot-clé dans le H1, contenu éditorial insuffisant, et navigation par collections plutôt que par attributs produit
2. La densité de mot-clé est faible sur l'ensemble du top 3 (Amazon: 1, GL: 0, Lacoste: 2), ce qui suggère que Google valorise surtout l'autorité de domaine et la pertinence structurelle pour cette requête — un enrichissement sémantique modéré (H1 + sous-titres + texte éditorial) pourrait suffire à gagner la position #2
3. Aucun des trois leaders n'exploite les données structurées de manière optimale — c'est un levier de différenciation immédiat pour Lacoste`,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. MENS DESIGNER JACKET — US — Lacoste absent
  // ═══════════════════════════════════════════════════════════════════════════
  {
    run_id: RUN_ID,
    keyword_id: 'd8601551-fe2c-494e-885e-8152c72fce75',
    country: 'US',
    device: 'mobile',
    analysis_type: 'lacoste_gap',
    lacoste_position: null,
    search_intent: 'transactional',
    opportunity_score: 4,
    tags: ['search_intent_mismatch', 'content_coverage', 'structure_hn', 'meta_title', 'structured_data'],
    sources: [
      { position: 1, domain: 'www.neimanmarcus.com', actor_name: 'Neiman Marcus', url: 'https://www.neimanmarcus.com/c/clothing-clothing-coats-jackets-cat14810731' },
      { position: 2, domain: 'www.saksfifthavenue.com', actor_name: 'Saks Fifth Avenue', url: 'https://www.saksfifthavenue.com/c/men/apparel/coats-jackets' },
      { position: 3, domain: 'www.farfetch.com', actor_name: 'Farfetch', url: 'https://www.farfetch.com/shopping/men/jackets-2/items.aspx' },
      { position: 4, domain: 'row.burberry.com', actor_name: 'Burberry', url: 'https://row.burberry.com/l/mens-coats-jackets/' },
      { position: 5, domain: 'www.macys.com', actor_name: "Macy's", url: 'https://www.macys.com/shop/featured/mens-designer-jackets' },
      { position: 6, domain: 'www.ralphlauren.com', actor_name: 'Ralph Lauren', url: 'https://www.ralphlauren.com/men-clothing-jackets-coats-vests' },
      { position: 7, domain: 'www.umitbenan.com', actor_name: 'Umit Benan', url: 'https://www.umitbenan.com/collections/jackets-men' },
      { position: 8, domain: 'en.louisvuitton.com', actor_name: 'Louis Vuitton', url: 'https://en.louisvuitton.com/eng-nl/men/ready-to-wear/outerwear-and-coats/_/N-t1epdz97' },
      { position: 9, domain: 'us.louisvuitton.com', actor_name: 'Louis Vuitton', url: 'https://us.louisvuitton.com/eng-us/men/ready-to-wear/coats/_/N-t1epdz97' },
      { position: 10, domain: 'www.amazon.com', actor_name: 'Amazon', url: 'https://www.amazon.com/Mens-Designer-Jackets/s?k=Men%27s+Designer+Jackets' },
    ],
    content: `### Alignement intention
- La requête "mens designer jacket" est transactionnelle haut de gamme — l'utilisateur recherche des vestes de créateurs, ce qui positionne le résultat dans le segment luxe/premium
- La SERP est dominée par des **retailers luxe américains** : **Neiman Marcus** (#1), **Saks Fifth Avenue** (#2), **Farfetch** (#3) — positionnement ultra-premium ($600-$16,000)
- Les **brands luxe** arrivent ensuite : **Burberry** (#4), **Ralph Lauren** (#6), **Louis Vuitton** (#8-9), **Umit Benan** (#7)
- **Lacoste est absent du top 50** — la marque n'est pas perçue par Google comme un acteur du segment "designer jacket" sur le marché américain
- Ce positionnement est cohérent avec le pricing Lacoste (segment premium accessible vs ultra-luxe), mais représente un manque à gagner sur les requêtes aspirationnelles

### Couverture sémantique
- Fait remarquable : **aucun des 10 résultats** ne contient l'expression exacte "mens designer jacket" dans son contenu — densité à 0 pour tous
- Les résultats se positionnent via des variantes sémantiques : "Men's Designer Coats, Jackets & Vests" (Neiman Marcus), "Designer Jackets for Men" (Farfetch)
- **Farfetch** (#3) se distingue avec un paragraphe éditorial citant Moncler, Burberry, Carhartt WIP et The North Face comme références, créant un contexte sémantique riche
- **Ralph Lauren** (#6) propose un texte descriptif développé mentionnant Purple Label, windbreakers, leather jackets et puffer vests — enrichissant la couverture sémantique
- L'absence de densité exacte du mot-clé sur cette SERP indique que Google privilégie la pertinence sémantique large et l'autorité de marque pour les requêtes "designer"

### Structure
- Format uniformément PLP (Product Listing Page) avec navigation par sous-catégories (bombers, puffers, leather, lightweight)
- **Neiman Marcus** et **Saks** proposent des visual filters (images de sous-catégories cliquables) — UX premium
- **Louis Vuitton** structure par collections (Fall-Winter, Pre-Fall, Spring) et par styles (Blouson, Bombers, Coats, Denim) — approche fashion-forward
- **Farfetch** affiche les produits avec marques, descriptions et prix dès la page catégorie
- **Macy's** (#5) retourne une page "Access Denied" (Akamai) — snapshot indisponible, probablement un blocage bot

### Optimisation meta
- Les title tags sont optimisés avec "Designer" en position initiale : "Men's Designer Coats, Jackets & Vests" (NM), "Men's Designer Coats & Jackets" (Saks)
- Les snippets incluent des noms de marques (Stone Island, Moncler) et des prix pour maximiser le CTR
- **Burberry** utilise un title distinctif avec le symbole ®️ officiel
- L'absence de Lacoste signifie qu'aucune optimisation meta n'est possible sans création préalable d'une page dédiée au marché US

### Données structurées
- **Farfetch** (#3) déploie le balisage le plus riche : **Product x96**, **Brand x96**, **Offer x96**, **MerchantReturnPolicy x96** — un schema par produit sur la page catégorie
- **Neiman Marcus** (#1) implémente SiteNavigationElement x13 + BreadcrumbList — orientation navigation
- **Ralph Lauren** (#6) utilise Organization + ContactPoint + WebSite + SearchAction + **ItemList** + BreadcrumbList x27 — balisage complet mais sans Product/Offer
- **Louis Vuitton** (#8-9) utilise ItemList + ListItem (26-27) + BreadcrumbList — structuration de la liste produit
- **Amazon** et **Macy's** : aucune donnée structurée détectée

## Recommandations
1. Créer une page catégorie dédiée "Designer Jackets for Men" sur lacoste.com/en-us ciblant le marché américain, avec du contenu éditorial positionnant Lacoste comme marque de designer outerwear
2. Implémenter des schemas Product + Offer + Brand sur cette page pour rivaliser avec Farfetch en termes de rich snippets
3. Inclure du contenu éditorial citant les lignes iconiques Lacoste (Heritage, Sport) et les matériaux (Gore-Tex, waterproof) pour enrichir la couverture sémantique
4. La difficulté de cette SERP est élevée (concurrents ultra-premium avec forte autorité de domaine) — prioriser les quick wins sur d'autres keywords avant d'attaquer celui-ci
5. Explorer une stratégie d'indexation via les retailers US qui vendent déjà Lacoste (Macy's, Nordstrom) pour capter du trafic indirect`,
  },

  {
    run_id: RUN_ID,
    keyword_id: 'd8601551-fe2c-494e-885e-8152c72fce75',
    country: 'US',
    device: 'mobile',
    analysis_type: 'top3_deep_dive',
    lacoste_position: null,
    tags: ['meta_title', 'content_depth', 'structure_hn', 'structured_data', 'meta_description'],
    sources: [
      { position: 1, domain: 'www.neimanmarcus.com', actor_name: 'Neiman Marcus', url: 'https://www.neimanmarcus.com/c/clothing-clothing-coats-jackets-cat14810731' },
      { position: 2, domain: 'www.saksfifthavenue.com', actor_name: 'Saks Fifth Avenue', url: 'https://www.saksfifthavenue.com/c/men/apparel/coats-jackets' },
      { position: 3, domain: 'www.farfetch.com', actor_name: 'Farfetch', url: 'https://www.farfetch.com/shopping/men/jackets-2/items.aspx' },
    ],
    content: `### Analyse des titles
- **Neiman Marcus** (#1) : H1 = "Men's Designer Coats, Jackets & Vests" — inclusif (coats + jackets + vests), title tag identique au H1 avec suffixe "- Neiman Marcus"
- **Saks Fifth Avenue** (#2) : H1 = "Men's Designer Coats & Jackets" — plus concis, 1 292 items listés. Le breadcrumb Men > Clothing > Coats & Jackets renforce la structure
- **Farfetch** (#3) : H1 = "Designer Jackets for Men" — formulation inversée ("for Men" vs "Men's"), accompagné d'un paragraphe éditorial riche mentionnant Moncler, Burberry, The North Face, Carhartt WIP
- Les trois leaders utilisent "Designer" dans leur H1, confirmant que ce qualificatif est essentiel pour se positionner sur cette requête

### Profondeur de contenu
- **Neiman Marcus** (#1) : texte éditorial structuré mentionnant "sleek parkas", "long coats", "stylish bomber jackets", "denim jackets", "cashmere coats" et "suede safari" — bon enrichissement sémantique sous le H1. Densité mot-clé exact = 0 (utilise des variantes)
- **Saks Fifth Avenue** (#2) : pas de contenu éditorial visible — la page est un pure listing produit avec tri (Featured, Best Sellers, Newest, Price) et filtres (Designer, Price, Size, Color, Sale). 1 292 produits avec navigation visuelle par sous-catégories (Bombers & Varsity, Puffers, Leather & Shearling, Lightweight)
- **Farfetch** (#3) : paragraphe éditorial de qualité citant des marques et des produits spécifiques ("Moncler puffer jackets", "Burberry trench coats", "Carhartt WIP Detroit shirt jacket"). Premiers produits visibles : FENDI ($16,905), LEMAIRE ($2,841), Prada ($10,500) — positionnement ultra-luxe
- Farfetch se distingue par sa capacité à combiner contenu éditorial et listing produit premium

### Structure
- **Neiman Marcus** : carrousel promotionnel en header (free shipping, gift card, spring sale), puis H1, contenu éditorial, et grille produit. Promotional-heavy mais fonctionnel
- **Saks Fifth Avenue** : navigation visuelle par sous-catégories en carrousel d'images, breadcrumb clair, puis filtre/tri avancé avec model view toggle (on/off). Le plus clean des trois en termes d'UX
- **Farfetch** : bannières promo (15% off pre-owned, 15% off first app order), H1 + paragraphe éditorial, puis grille produit avec prix et disponibilité taille. Focus sur le contenu éditorial

### Données structurées
- **Neiman Marcus** (#1) : SiteNavigationElement x13 + BreadcrumbList + ListItem x3 — balisage orienté navigation
- **Saks Fifth Avenue** (#2) : BreadcrumbList + ListItem x3 — balisage minimal
- **Farfetch** (#3) : **ItemList + Product x96 + Brand x96 + Offer x96 + MerchantReturnPolicy x96** + BreadcrumbList — balisage le plus complet du top 3, avec un schema Product pour chaque veste affichée
- La stratégie de Farfetch en termes de structured data est un modèle à suivre : chaque produit balisé individuellement avec prix, marque et politique de retour

### Optimisation meta
- **Neiman Marcus** : snippet riche mentionnant "sleek parkas and long coats" et les sous-catégories disponibles
- **Saks Fifth Avenue** : snippet produit avec marques et prix ("Stone Island · Cotton Military Shirt · $640", "Gorski · Apres-Ski Jacket")
- **Farfetch** : snippet avec USP ("express shipping ✈", "Free returns") et marques (Moncler, The North Face, Carhartt) — le plus engageant pour le CTR

## Points clés
1. Cette SERP est un **terrain ultra-concurrentiel** dominé par des retailers luxe à forte autorité de domaine — Lacoste y est absent car non perçu comme acteur "designer" aux US
2. **Farfetch** est le benchmark en termes d'implémentation SEO : contenu éditorial + structured data complètes + produits premium mis en avant
3. L'opportunité pour Lacoste est limitée sur ce mot-clé exact (score 4/10) — une stratégie de contenu sur des requêtes plus ciblées ("lightweight jacket men", "cotton windbreaker mens") serait plus réaliste`,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. POLO HOMME — FR — Lacoste absent
  // ═══════════════════════════════════════════════════════════════════════════
  {
    run_id: RUN_ID,
    keyword_id: 'ee4aef3b-175c-4527-afba-da15f414d76b',
    country: 'FR',
    device: 'mobile',
    analysis_type: 'lacoste_gap',
    lacoste_position: null,
    search_intent: 'transactional',
    opportunity_score: 10,
    tags: ['search_intent_mismatch', 'content_coverage', 'content_depth', 'structure_hn', 'meta_title', 'structured_data'],
    sources: [
      { position: 1, domain: 'www.celio.com', actor_name: 'Celio', url: 'https://www.celio.com/fr-fr/c/polos' },
      { position: 2, domain: 'www.galerieslafayette.com', actor_name: 'Galeries Lafayette', url: 'https://www.galerieslafayette.com/c/homme/vetements/polos' },
      { position: 3, domain: 'www.eden-park.com', actor_name: 'Eden Park', url: 'https://www.eden-park.com/collections/polos' },
      { position: 4, domain: 'vicomte-a.com', actor_name: 'Vicomte A.', url: 'https://vicomte-a.com/collections/homme-polos' },
      { position: 5, domain: 'www.acanthe-paris.com', actor_name: 'Acanthe', url: 'https://www.acanthe-paris.com/homme-1/polos.html' },
      { position: 6, domain: 'boutique.asm-rugby.com', actor_name: 'ASM Clermont', url: 'https://boutique.asm-rugby.com/40-polos' },
      { position: 7, domain: 'www.replayjeans.com', actor_name: 'Replay', url: 'https://www.replayjeans.com/fr/homme/vetement/polo/' },
      { position: 8, domain: 'www.jules.com', actor_name: 'Jules', url: 'https://www.jules.com/fr-fr/l/polo/' },
      { position: 9, domain: 'www.sport2000.fr', actor_name: 'Sport 2000', url: 'https://www.sport2000.fr/taxons/sport-2000/selection-homme-sport-2000/vetements-homme/polos-homme' },
      { position: 10, domain: 'boutique.stadetoulousain.fr', actor_name: 'Stade Toulousain', url: 'https://boutique.stadetoulousain.fr/245-polos-' },
    ],
    content: `### Alignement intention
- La requête "polo homme" est **LA requête signature de Lacoste** — la marque a littéralement inventé le polo moderne. Son absence du top 50 est un échec SEO critique
- La SERP est dominée par des **marques françaises mid-market** : **Celio** (#1), **Eden Park** (#3), **Vicomte A.** (#4), **Jules** (#8) — aucune marque premium internationale
- **Galeries Lafayette** (#2, retailer) et **Sport 2000** (#9, retailer) sont les seuls multi-marques. Sport 2000 liste **93 produits Lacoste** en première position de ses filtres marque !
- Des boutiques de clubs sportifs occupent le top 10 : **ASM Clermont** (#6) et **Stade Toulousain** (#10) — ce qui illustre la faiblesse concurrentielle de cette SERP
- L'absence de Lacoste est d'autant plus paradoxale que la marque vend ses polos via Sport 2000, Galeries Lafayette et Citadium mais que son propre site ne se positionne pas

### Couverture sémantique
- **Sport 2000** (#9) domine avec **18 occurrences** du mot-clé et un texte éditorial descriptif incluant "polo homme", "vestiaire sportif et casual", "matières respirantes"
- **Stade Toulousain** (#10) affiche **16 occurrences** dont **16 en H2** — optimisation agressive des headings (chaque nom de produit en H2 contient "polo homme")
- **ASM Clermont** (#6) comptabilise **10 occurrences** dans le body via les noms de produits ("Polo homme Peart", "Polo homme Paladdin")
- **Eden Park** (#3) atteint **5 occurrences** avec du contenu éditorial de qualité ("C'est la pièce indispensable du vestiaire masculin, avec sa maille piquée et ses détails brodés")
- **Jules** (#8) affiche **4 occurrences** dont 1 en H2
- **Celio** (#1) n'a que **3 occurrences** mais se positionne grâce à son H1 "Polos homme" + navigation par sous-catégories (manches longues, piqué, jersey, maille)
- **Galeries Lafayette** (#2) a **0 occurrence** — pure autorité de domaine

### Structure
- Format PLP standard avec des variantes selon la taille du catalogue : Celio (112 produits), Galeries Lafayette (multi-marques), Eden Park (142 produits), Jules (123 produits), Sport 2000 (444 produits)
- **Celio** se distingue par ses sous-catégories visuelles (pastilles cliquables : manches longues, à 15,99€, en maille, en piqué, en jersey)
- **Eden Park** combine texte éditorial + sous-catégories par longueur/couleur/matière + grille produit — le meilleur équilibre contenu/UX du top 10
- **Sport 2000** affiche le filtre "LACOSTE 93" en première position de ses marques, prouvant que Lacoste est la marque la plus vendue dans cette catégorie

### Optimisation meta
- Les title tags suivent le pattern "[Polo Homme] - [Nom marque]" pour tous les concurrents
- **Jules** se distingue avec un title enrichi : "Polo Homme - Nos polos unis, à motifs, coton, slim | Jules"
- **Vicomte A.** utilise un title aspirationnel : "Polo Homme Chic & Élégant : Haut de Gamme et Intemporel"
- **Sport 2000** inclut "Confort & Style Sportif" dans son title — positionnement sport/lifestyle

### Données structurées
- **Celio** (#1) : Product + aggregateRating + BreadcrumbList + ListItem x34 + ItemList — balisage complet
- **ASM Clermont** (#6) : ImageObject + Organization + WebPage + WebSite + BreadcrumbList x2 + ListItem x34 + ItemList — très riche
- **Stade Toulousain** (#10) : configuration similaire à ASM (PrestaShop standard)
- **Eden Park** (#3) : Organization + CreativeWorkSeries + AggregateRating — orientation marque mais pas de Product
- **Galeries Lafayette**, **Jules**, **Sport 2000**, **Acanthe** : aucune donnée structurée détectée

## Recommandations
1. **URGENCE** : créer/optimiser la page lacoste.com/fr/lacoste/homme/vetements/polos/ avec le H1 "Polos Homme" et l'expression exacte "polo homme" dans le title tag, H1, et au minimum 3-5 sous-titres H2
2. Rédiger un contenu éditorial de 150-250 mots positionnant Lacoste comme l'inventeur du polo (histoire, maille piquée L.12.12, innovation textile) — levier de différenciation unique qu'aucun concurrent ne peut revendiquer
3. Implémenter ItemList + Product + Offer + AggregateRating sur la page catégorie pour activer les rich snippets
4. Ajouter des liens internes depuis les pages les plus visitées (homepage FR, page homme) vers la page polos avec l'ancre "polo homme"
5. Créer des sous-catégories optimisées : "polo homme manches courtes", "polo homme manches longues", "polo homme coton piqué" — Eden Park le fait déjà avec succès
6. **Opportunité score 10/10** : la concurrence est faible (pas de géant type Amazon), Lacoste a la légitimité historique, et le volume de recherche est majeur`,
  },

  {
    run_id: RUN_ID,
    keyword_id: 'ee4aef3b-175c-4527-afba-da15f414d76b',
    country: 'FR',
    device: 'mobile',
    analysis_type: 'top3_deep_dive',
    lacoste_position: null,
    tags: ['meta_title', 'content_depth', 'structure_hn', 'structured_data', 'meta_description'],
    sources: [
      { position: 1, domain: 'www.celio.com', actor_name: 'Celio', url: 'https://www.celio.com/fr-fr/c/polos' },
      { position: 2, domain: 'www.galerieslafayette.com', actor_name: 'Galeries Lafayette', url: 'https://www.galerieslafayette.com/c/homme/vetements/polos' },
      { position: 3, domain: 'www.eden-park.com', actor_name: 'Eden Park', url: 'https://www.eden-park.com/collections/polos' },
    ],
    content: `### Analyse des titles
- **Celio** (#1) : H1 = "Polos homme" — minimaliste et exact. Title "Polo Homme: Polo uni, coloré, motifs | celio" avec variantes de recherche incluses
- **Galeries Lafayette** (#2) : H1 = "Polos homme" — identique à Celio. Title "Polos homme - Galeries Lafayette" simple avec brand suffix
- **Eden Park** (#3) : H1 = "Polos Homme" — même formulation. Title "Polo Homme - Eden Park" au singulier. Le contenu éditorial sous le H1 est un différenciateur : "C'est la pièce indispensable du vestiaire masculin..."
- Les trois leaders utilisent le même H1 exact "Polos homme" — Lacoste devrait suivre cette convention plutôt qu'un titre créatif

### Profondeur de contenu
- **Celio** (#1) : **3 occurrences** du mot-clé (dont 1 en H2), 112 produits. La page propose des sous-catégories visuelles (pastilles) : manches longues, à 15,99€, en maille, en piqué, en jersey + filtres avancés (catégorie, couleur, taille, coupe, col, longueur, matière, prix). Premier produit visible : "Polo piqué regular 100% coton - marine" à 15,99€
- **Galeries Lafayette** (#2) : **0 occurrence** du mot-clé dans le body. Navigation par marques exhaustive (A.P.C., Adidas by Wales Bonner, Agnès b., AMI Paris, Armor-Lux, Balmain, BOSS, C.P. Company...) + filtres taille et sous-catégories (manches courtes/longues). L'autorité de domaine compense l'absence totale d'optimisation sémantique
- **Eden Park** (#3) : **5 occurrences** dont 1 en H2 et 1 en H3. Texte éditorial sous le H1 : "C'est la pièce indispensable du vestiaire masculin, avec sa maille piquée et ses détails brodés ou imprimés". Sous-catégories SEO dédiées : "Polos Manches Longues Homme", "Polos Manches Courtes Homme", "Polos Blanc Homme", "Polos Noir Homme", "Polos Bleu Homme", "Polos Coton Pima"
- Eden Park est le benchmark contenu : texte éditorial + sous-catégories SEO + volume produit (142). Lacoste pourrait faire mieux avec son héritage historique unique

### Structure
- **Celio** : approche entrée de gamme avec prix agressifs (15,99€), filtrage riche (coupe slim/oversize/boxy/regular, col polo/zippé/mao/cubain), vue configurable (1-4 colonnes). Mobile-first
- **Galeries Lafayette** : pure agrégation multi-marques sans contenu éditorial. Navigation par marques (50+) et tailles. Le positionnement repose sur la profondeur de catalogue et l'autorité domaine
- **Eden Park** : le plus complet en termes d'UX — hero image en pleine largeur, texte éditorial, sous-catégories cliquables, tri multi-critères, cross-selling ("Les pantalons", "Les chemisettes"). Premier produit : "Polo à manches courtes en coton kaki coupe regular"

### Données structurées
- **Celio** (#1) : Product + aggregateRating + BreadcrumbList + ListItem x34 + ItemList — le balisage le plus complet du top 3 avec notation produit
- **Galeries Lafayette** (#2) : aucune donnée structurée détectée — l'autorité de domaine supplée
- **Eden Park** (#3) : Organization + CreativeWorkSeries + AggregateRating — balisage orienté marque mais pas de Product individuel
- Celio a le meilleur balisage mais Eden Park a le meilleur contenu — combiner les deux approches serait optimal

### Optimisation meta
- **Celio** : snippet incluant "Paiement sécurisé ✓ Retrait gratuit en magasin ✓ Livraison rapide" — USP transactionnelles avec checkmarks
- **Galeries Lafayette** : snippet sobre "Découvrez notre large sélection... Livraison Gratuite en magasin ou dès 100€"
- **Eden Park** : snippet avec "Paiement Sécurisé ✔️ Livraison Gratuite dès 99 €" — format similaire à Celio

## Points clés
1. **L'absence de Lacoste sur "polo homme" est la lacune SEO la plus critique identifiée** — la marque a inventé le polo et devrait dominer cette SERP. Les concurrents actuels sont des marques mid-market (Celio, Jules, Eden Park) qui n'ont pas la légitimité historique de Lacoste
2. **Eden Park** est le modèle à suivre : texte éditorial évocateur + sous-catégories SEO dédiées (par couleur, longueur, matière) + volume produit conséquent
3. **Sport 2000** (#9) vend 93 polos Lacoste et les met en avant en premier filtre marque — preuve que la demande existe massivement mais que le site Lacoste ne la capte pas directement`,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. SNEAKERS HOMME — FR — Lacoste absent
  // ═══════════════════════════════════════════════════════════════════════════
  {
    run_id: RUN_ID,
    keyword_id: 'ff72f1b8-2c6e-4cb3-a5b8-7df92434b8e9',
    country: 'FR',
    device: 'mobile',
    analysis_type: 'lacoste_gap',
    lacoste_position: null,
    search_intent: 'transactional',
    opportunity_score: 7,
    tags: ['search_intent_mismatch', 'content_coverage', 'content_depth', 'structure_hn', 'structured_data'],
    sources: [
      { position: 1, domain: 'wethenew.com', actor_name: 'Wethenew', url: 'https://wethenew.com/collections/sneakers-homme' },
      { position: 2, domain: 'www.citadium.com', actor_name: 'Citadium', url: 'https://www.citadium.com/fr/fr/sneakers-homme' },
      { position: 3, domain: 'www.zalando.fr', actor_name: 'Zalando', url: 'https://www.zalando.fr/baskets-homme/' },
      { position: 4, domain: 'jmweston.com', actor_name: 'J.M. Weston', url: 'https://jmweston.com/fr/collections/baskets-et-sneakers-noires-pour-homme' },
      { position: 5, domain: 'www.sneakerdistrict.fr', actor_name: 'Sneaker District', url: 'https://www.sneakerdistrict.fr/homme/sneakers' },
      { position: 6, domain: 'www.intersport.fr', actor_name: 'Intersport', url: 'https://www.intersport.fr/sportswear/homme/chaussures/sneakers/' },
      { position: 7, domain: 'fr.burberry.com', actor_name: 'Burberry', url: 'https://fr.burberry.com/l/chaussures-homme/sneakers/' },
      { position: 8, domain: 'www.lecoqsportif.com', actor_name: 'Le Coq Sportif', url: 'https://www.lecoqsportif.com/collections/baskets-homme' },
      { position: 9, domain: 'www.skechers.fr', actor_name: 'Skechers', url: 'https://www.skechers.fr/homme/chaussures/baskets/' },
      { position: 10, domain: 'www.berluti.com', actor_name: 'Berluti', url: 'https://www.berluti.com/fr-fr/souliers/baskets/' },
    ],
    content: `### Alignement intention
- La requête "sneakers homme" est transactionnelle avec un volume de recherche majeur — l'utilisateur cherche à acheter des baskets
- La SERP mélange **retailers spécialisés sneakers** (#1 Wethenew, #2 Citadium, #3 Zalando, #5 Sneaker District, #6 Intersport) et **brands** (#4 J.M. Weston, #7 Burberry, #8 Le Coq Sportif, #9 Skechers, #10 Berluti)
- **Lacoste est absent du top 50** malgré un catalogue sneakers conséquent — **Citadium** (#2) liste **25 sneakers Lacoste** dans ses filtres marque, et **Zalando** (#3) affiche une sneaker Lacoste sponsorisée en premier résultat
- Les retailers vendent des sneakers Lacoste avec succès, mais le site Lacoste ne se positionne pas sur cette requête générique

### Couverture sémantique
- **Intersport** (#6) affiche un volume extraordinaire de **176 occurrences** du mot-clé "sneakers homme" avec le mot-clé en H1 — optimisation extrême via les noms de produits et descriptions
- **Citadium** (#2) atteint **5 occurrences** dont 2 en H2, avec un paragraphe éditorial engageant au ton décontracté : "Tu cherches la paire qui va faire toute la différence sur le bitume ?"
- **Wethenew** (#1) comptabilise **4 occurrences** dont 1 en H1 "Sneakers Homme"
- **Zalando** (#3) n'a **0 occurrence** du mot-clé exact mais se positionne avec "Sneakers pour homme" en H1 — variante sémantique proche
- **Burberry** (#7) a **1 occurrence** en H1 "Sneakers Homme" + un paragraphe éditorial riche décrivant les collections (Burberry Check, Equestrian Knight Design, Knight Blue)
- **Le Coq Sportif** (#8) retourne une **page d'erreur** — snapshot indisponible
- **Berluti** (#10) est bloqué par Akamai — idem

### Structure
- **Wethenew** se distingue par une navigation par univers (Sneakers, Streetwear, Wellness, Active, Chaussures, Sacs De Luxe Vintage, Collectibles) — positionnement lifestyle au-delà de la sneaker
- **Citadium** propose un filtre marque exhaustif (Adidas 139, Nike 45, New Balance 81, Asics 63, **Lacoste 25**) avec 837 produits
- **Zalando** offre 15 264 articles avec filtres ultra-fins (marque, taille, couleur, propriétés, prix, matière, largeur de chaussure, système de fixation, forme du talon)
- **Burberry** structure sa page avec texte éditorial + grille produit (31 articles) + filtres, en incluant une description par modèle (Box sneaker, Equestrian Knight)
- **Sneaker District** propose une navigation technique (matière : cuir/suède/synthétique/textile, pointure 34-50, couleur 18 options)

### Optimisation meta
- **Wethenew** : title incluant "Large Choix de Baskets Tendances" et snippet mentionnant "livraison offerte à partir de 200€"
- **Citadium** : snippet ciblant les marques hype "Asics, Autry, Veja ou New Balance" pour maximiser le CTR
- **Burberry** : title avec "Site officiel Burberry®" et symbole de marque déposée

### Données structurées
- **Wethenew** (#1) : balisage très riche — WebSite + SearchAction + ItemList x2 + **Product x41** + Brand + Review + AggregateRating + **Offer x1387** + ListItem x40 — le leader en structuration
- **Citadium** (#2) : WebSite + SearchAction + ItemList + **Product x60** + Brand x60 + **Offer x60** + Organization x60 + ListItem x64 + BreadcrumbList — comparable à Wethenew
- **Sneaker District** (#5) : CollectionPage + Product x6 + Brand x6 + Offer x6 + Organization + AggregateRating + BreadcrumbList
- **Zalando** (#3), **Le Coq Sportif** (#8), **Skechers** (#9) : pas de données structurées détectées ou balisage minimal

## Recommandations
1. Créer une page catégorie dédiée lacoste.com/fr/lacoste/homme/chaussures/sneakers/ avec H1 "Sneakers Homme" et contenu éditorial positionnant les modèles Lacoste (Powercourt, L001, Carnaby)
2. Implémenter des schemas Product + Offer + AggregateRating à l'image de Wethenew et Citadium — c'est un prérequis pour rivaliser sur cette SERP
3. Ajouter du contenu éditorial décrivant les technologies Lacoste (OrthoLite, matériaux recyclés) et les collections signature
4. Cibler les sous-catégories : "sneakers blanches homme", "baskets cuir homme", "sneakers lacoste homme" — requêtes avec moins de concurrence
5. Mettre en place un maillage interne depuis les pages produit sneakers individuelles vers la page catégorie
6. L'opportunité est réelle (7/10) : le marché est gros mais dominé par des retailers multi-marques qui vendent déjà Lacoste — capter ce trafic en direct est stratégique`,
  },

  {
    run_id: RUN_ID,
    keyword_id: 'ff72f1b8-2c6e-4cb3-a5b8-7df92434b8e9',
    country: 'FR',
    device: 'mobile',
    analysis_type: 'top3_deep_dive',
    lacoste_position: null,
    tags: ['meta_title', 'content_depth', 'structure_hn', 'structured_data', 'meta_description'],
    sources: [
      { position: 1, domain: 'wethenew.com', actor_name: 'Wethenew', url: 'https://wethenew.com/collections/sneakers-homme' },
      { position: 2, domain: 'www.citadium.com', actor_name: 'Citadium', url: 'https://www.citadium.com/fr/fr/sneakers-homme' },
      { position: 3, domain: 'www.zalando.fr', actor_name: 'Zalando', url: 'https://www.zalando.fr/baskets-homme/' },
    ],
    content: `### Analyse des titles
- **Wethenew** (#1) : H1 absent dans le contenu visible (la page commence par une navigation visuelle par univers). Title "Sneakers Homme - Large Choix de Baskets Tendances - Wethenew" — double mot-clé (sneakers + baskets) pour capter les deux variantes
- **Citadium** (#2) : H1 = "Baskets & Sneakers Homme" — double formulation couvrant les deux termes de recherche. Paragraphe éditorial immédiatement sous le H1 au ton urbain/décontracté
- **Zalando** (#3) : H1 = "Sneakers pour homme" — variante avec "pour homme" au lieu de la forme composée. Title "Sneakers pour homme - Zalando" simple et efficace
- Point clé : Wethenew et Citadium utilisent les deux termes (sneakers + baskets) pour maximiser la couverture sémantique — stratégie à reproduire

### Profondeur de contenu
- **Wethenew** (#1) : **4 occurrences** du mot-clé dont 1 en H1. Pas de contenu éditorial classique — la page est un hub de navigation visuel avec sélections curatées (Les Nouveautés, Les Essentiels Sneakers, Les Meilleures Collaborations, Travis Scott). Modèle resale/marketplace avec positionnement lifestyle
- **Citadium** (#2) : **5 occurrences** dont 2 en H2. Paragraphe éditorial engageant : "Tu cherches la paire qui va faire toute la différence sur le bitume ? T'es au bon endroit." Filtre marque riche avec **Lacoste listé à 25 produits** parmi 837 au total. Contenu plus riche que Wethenew
- **Zalando** (#3) : **0 occurrence** du mot-clé exact. 15 264 articles avec une première sneaker sponsorisée **Lacoste Powercourt 125** en position 1 du listing ! Filtres exhaustifs mais pas de contenu éditorial
- Fait notable : Zalando sponsorise une sneaker Lacoste en premier résultat de sa catégorie, prouvant la demande pour la marque

### Structure
- **Wethenew** : approche lifestyle premium — navigation par univers visuels (Sneakers, Streetwear, Wellness, Active), sélections curatées (Travis Scott, best-sellers), livraison 48h badge. Focus sur les marques hype et les collaborations exclusives
- **Citadium** : approche streetwear — Hot Deals banner, breadcrumb clair (Accueil > Homme > Footwear > Sneakers), puis texte éditorial + filtres/tri (837 produits). Filtre marque avec Lacoste à 25 paires
- **Zalando** : approche généraliste massive — 15 264 articles, filtres ultra-détaillés (marque, taille, couleur, propriétés, prix, matière, largeur, fixation, forme du talon), sous-catégories (basses/montantes/skate). Le plus exhaustif en termes de catalogue

### Données structurées
- **Wethenew** (#1) : WebSite + SearchAction + ItemList x2 + **Product x41** + Brand + Review + Person + Rating + AggregateRating + **Offer x1387** (!) + ListItem x40 — balisage extrêmement détaillé avec avis et offres multiples par produit (modèle marketplace)
- **Citadium** (#2) : WebSite + SearchAction + ItemList + **Product x60** + Brand x60 + Offer x60 + Organization x60 + ListItem x64 + BreadcrumbList — un schema Product/Brand/Offer par produit affiché
- **Zalando** (#3) : aucune donnée structurée détectée — Zalando s'appuie sur son autorité de domaine et ses liens sponsorisés
- Le modèle Wethenew/Citadium (Product + Offer par produit) est le benchmark à atteindre pour Lacoste

### Optimisation meta
- **Wethenew** : snippet court "Paiement en plusieurs fois et livraison offerte à partir de 200€ d'achat" — USP transactionnelles
- **Citadium** : snippet mentionnant les marques hype "Asics, Autry, Veja ou New Balance" — name-dropping pour le CTR
- **Zalando** : snippet standard "Livraisons et retours gratuits" + "Des milliers" de choix

## Points clés
1. Les **retailers spécialisés** dominent cette SERP, pas les marques — Lacoste doit se positionner en tant que marque d'autorité avec un contenu éditorial fort pour se différencier du catalogue multi-marques
2. **Citadium vend déjà 25 sneakers Lacoste** et **Zalando sponsorise la Powercourt en position 1** — la demande consommateur existe, Lacoste doit la capter directement
3. Le balisage Product + Offer détaillé (comme Wethenew avec 1 387 Offers) est devenu le standard de cette SERP — un prérequis pour la compétitivité`,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. MENS POLO SHIRT — US — Lacoste absent
  // ═══════════════════════════════════════════════════════════════════════════
  {
    run_id: RUN_ID,
    keyword_id: 'd7caa77f-9786-48fa-8a2e-abee124e1fa1',
    country: 'US',
    device: 'mobile',
    analysis_type: 'lacoste_gap',
    lacoste_position: null,
    search_intent: 'transactional',
    opportunity_score: 9,
    tags: ['search_intent_mismatch', 'content_coverage', 'structure_hn', 'meta_title', 'structured_data'],
    sources: [
      { position: 1, domain: 'www.macys.com', actor_name: "Macy's", url: 'https://www.macys.com/shop/mens/clothing/shirts/polos?id=20640' },
      { position: 2, domain: 'www.ralphlauren.com', actor_name: 'Ralph Lauren', url: 'https://www.ralphlauren.com/men-clothing-polo-shirts' },
      { position: 3, domain: 'southerntide.com', actor_name: 'Southern Tide', url: 'https://southerntide.com/collections/men-polos' },
      { position: 4, domain: 'www.elganso.com', actor_name: 'El Ganso', url: 'https://www.elganso.com/intl_en/men/polos.html' },
      { position: 5, domain: 'www.musto.com', actor_name: 'Musto', url: 'https://www.musto.com/en_us/mens/t-shirts-polos' },
      { position: 6, domain: 'www.tomfordfashion.com', actor_name: 'Tom Ford', url: 'https://www.tomfordfashion.com/en-us/men/ready-to-wear/polos-t-shirts/' },
      { position: 7, domain: 'www.dunhill.com', actor_name: 'Dunhill', url: 'https://www.dunhill.com/en-us/cat/ready-to-wear/polos/' },
      { position: 8, domain: 'us.sandro-paris.com', actor_name: 'Sandro', url: 'https://us.sandro-paris.com/en/mens/clothing/tshirts-polos/' },
      { position: 9, domain: 'www.tentree.com', actor_name: 'Tentree', url: 'https://www.tentree.com/collections/mens-polo-shirts' },
      { position: 10, domain: 'www.northsails.com', actor_name: 'North Sails', url: 'https://www.northsails.com/en-us/collections/men-polos' },
    ],
    content: `### Alignement intention
- La requête "mens polo shirt" est l'équivalent US de "polo homme" — transactionnelle, à très fort volume, et historiquement associée à Lacoste et Ralph Lauren
- **Ralph Lauren** (#2) est le seul concurrent direct de Lacoste présent dans le top 10 — snapshot indisponible mais positionnement confirmé
- **Macy's** (#1) est bloqué par Akamai — son contenu n'est pas analysable
- La SERP est dominée par des **brands niche/premium** : Southern Tide (preppy americana), El Ganso (espagnol), Musto (nautique), Tom Ford (ultra-luxe), Dunhill (luxe britannique), Sandro (contemporain français), Tentree (éco-responsable), North Sails (voile)
- **L'absence de Lacoste est stupéfiante** — la marque a inventé le polo et devrait être dans le top 3 mondial pour cette requête aux US

### Couverture sémantique
- **0 occurrence** du mot-clé exact "mens polo shirt" sur l'ensemble des 10 résultats — densité nulle pour tous les concurrents
- Les résultats se positionnent via des variantes : "Men's Polo Shirts" (Macy's, RL), "Men's Polo Shirts & T-Shirts" (Musto), "Men's Polos & T-Shirts" (Tom Ford)
- **Musto** (#5) se distingue avec du contenu éditorial : "quick-dry fabric to keep you feeling comfortable on land and out at sea" — positionnement fonctionnel/nautique
- **Tom Ford** (#6) utilise un ton aspirationnel : "Elevate everyday refinement with TOM FORD men's designer polo shirts" — positionnement luxe
- **Tentree** (#9) se différencie par le message éco-responsable : "EVERY ITEM PLANTS 10 TREES" et "sustainable fabrics like hemp, recycled polyester, organic cotton"
- **Dunhill** (#7) utilise un H1 distinctif : "DUNHILL LUXURY MEN'S POLO" avec "engineered for comfort and practicality"

### Structure
- Format uniformément PLP avec catalogues de taille variable : Tom Ford (50 produits), Dunhill (32), Sandro (76)
- **Musto** : contient des liens vers sous-catégories lifestyle/sailing et produits à prix barrés ($29.25 was $65.00) — conversion-optimized
- **Tom Ford** : filtrage par type (Crewnecks, Henleys, Leather Jackets, Polo Shirts, T-Shirts), couleur (8 options), taille — navigation claire
- **Dunhill** : filtrage par couleur (9 options) et taille (XS-4X) avec 32 produits — catalogue réduit mais premium
- **Sandro** : 76 produits avec filtre par style (Polos vs T-shirts), couleur et taille — sous-catégorie dédiée

### Optimisation meta
- Les title tags varient entre formats : "Men's Polo Shirts - [Brand]" (standard), "Men's Polos & T-Shirts | [Brand]" (regroupé), "Men's Polo Shirts | Short & Long Sleeve Polos | dunhill US" (enrichi)
- Les snippets les plus efficaces incluent des USP transactionnelles (Musto: "$29.25", Southern Tide: "Complimentary Shipping on $150+")
- La formulation "polo shirt" (2 mots) vs "polo" (1 mot) est un choix éditorial : les marques UK/US préfèrent "polo shirt", les marques françaises utilisent "polo"

### Données structurées
- **Sandro** (#8) : le balisage le plus riche — BreadcrumbList + ListItem x36 + ItemList x2 + ImageObject + Product + Brand + AggregateOffer + Organization x2 + Corporation + WebSite
- **North Sails** (#10) : BreadcrumbList + ListItem x18 + Organization + PostalAddress + WebPage + SpeakableSpecification + ItemList — balisage très complet
- **Macy's** (#1), **Ralph Lauren** (#2), **Tom Ford** (#6), **Tentree** (#9) : aucune donnée structurée détectée ou balisage minimal
- L'absence de structured data chez les leaders (Macy's, RL) indique que l'autorité de marque suffit pour se positionner — mais c'est un levier supplémentaire pour un nouvel entrant

## Recommandations
1. **PRIORITÉ MAXIMALE** : optimiser la page us.lacoste.com dédiée aux polos hommes pour cibler "mens polo shirt" — Lacoste EST le polo. Cette requête devrait être un monopole naturel
2. Utiliser le heritage Lacoste comme contenu éditorial : "Since 1933, Lacoste has defined the polo shirt" — aucun concurrent ne peut revendiquer cette légitimité
3. Cibler un title tag comme "Men's Polo Shirts | The Original Polo Since 1933 | LACOSTE" pour se différencier des marques niche
4. Implémenter Product + Offer + Brand + AggregateRating sur chaque polo listé
5. Créer des sous-catégories ciblées : "classic fit polo", "slim fit polo", "long sleeve polo", "cotton piqué polo" — chacune correspondant à des requêtes secondaires à fort volume
6. **Opportunité score 9/10** : la concurrence est fragmentée entre marques niche sans leader dominant (Ralph Lauren mis à part), et Lacoste a la légitimité historique absolue`,
  },

  {
    run_id: RUN_ID,
    keyword_id: 'd7caa77f-9786-48fa-8a2e-abee124e1fa1',
    country: 'US',
    device: 'mobile',
    analysis_type: 'top3_deep_dive',
    lacoste_position: null,
    tags: ['meta_title', 'content_depth', 'structure_hn', 'structured_data', 'meta_description'],
    sources: [
      { position: 1, domain: 'www.macys.com', actor_name: "Macy's", url: 'https://www.macys.com/shop/mens/clothing/shirts/polos?id=20640' },
      { position: 2, domain: 'www.ralphlauren.com', actor_name: 'Ralph Lauren', url: 'https://www.ralphlauren.com/men-clothing-polo-shirts' },
      { position: 3, domain: 'southerntide.com', actor_name: 'Southern Tide', url: 'https://southerntide.com/collections/men-polos' },
    ],
    content: `### Analyse des titles
- **Macy's** (#1) : Title "Men's Polo Shirts - Macy's" — simple, direct. Le contenu réel est bloqué par Akamai (page "Powered and protected by Akamai"), rendant toute analyse de H1 impossible
- **Ralph Lauren** (#2) : Title "Men's Polo Shirts - Long & Short Sleeve Polos | Ralph Lauren" — enrichi avec variantes (Long & Short Sleeve). Snapshot non disponible — le serveur a bloqué le scraping
- **Southern Tide** (#3) : Title "Men's Performance & Cotton Polo Shirts - Southern Tide" — différenciation par matériau (Performance & Cotton). Pas de H1 visible dans le contenu scrappé (la page charge du contenu dynamique qui n'a pas été capté)
- Point critique : les 2 premiers résultats sont inaccessibles au scraping, ce qui limite l'analyse. Cela dit, leurs title tags seuls révèlent les patterns gagnants

### Profondeur de contenu
- **Macy's** (#1) : contenu indisponible (page Akamai). Basé sur le snippet Google "These classic options are perfect for a preppy and timeless look", Macy's positionne les polos comme classiques/preppy. **0 occurrence** du mot-clé dans le snapshot
- **Ralph Lauren** (#2) : contenu indisponible (snapshot manquant). Le snippet Google "Shop men's polo shirts and find everything from performance polos to classic polo shirts. Free Shipping With an RL Account" indique un positionnement large (performance + classic) avec USP livraison gratuite. **0 occurrence** du mot-clé
- **Southern Tide** (#3) : snippet "From performance to cotton polos, find your fit. Men's shirts made for effortless style and movement - on and off the golf course" — positionnement golf/outdoor lifestyle. **0 occurrence** du mot-clé. Le contenu visible est surtout du UI Shopify (panier, wishlist, rewards program)
- Les 3 leaders ont 0 densité de mot-clé — Google se base uniquement sur l'autorité de domaine et les signaux de pertinence sémantique (URL, title, catégorie)

### Structure
- **Macy's** : structure inaccessible — probable PLP multi-marques classique avec filtres (marque, taille, couleur, prix). En tant que retailer #1 US, Macy's bénéficie d'un catalogue massif incluant certainement Lacoste
- **Ralph Lauren** : probable PLP mono-marque avec segmentation par fit (Classic, Slim, Custom), sleeve (Long, Short), et collection. RL est le concurrent direct de Lacoste sur le segment polo
- **Southern Tide** : boutique Shopify avec programme de fidélité (Southern Tide Rewards), programme de revente (reclaimed/resale), navigation par collection. Cible le segment preppy/côtier américain avec un pricing accessible ($150 = free shipping). Le contenu dynamique n'a pas été capté par le scraper

### Données structurées
- **Macy's** (#1) : aucune donnée structurée détectée (page Akamai bloquée)
- **Ralph Lauren** (#2) : aucune donnée structurée détectée (snapshot indisponible)
- **Southern Tide** (#3) : Organization seulement — balisage minimal
- L'absence totale de structured data dans le top 3 est une opportunité majeure : Lacoste pourrait dominer les rich snippets en implémentant Product + Offer + AggregateRating dès son entrée sur cette SERP

### Optimisation meta
- **Macy's** : snippet standard e-commerce "Stay stylish and comfortable with Macy's collection... These classic options are perfect for a preppy and timeless look. Shop now."
- **Ralph Lauren** : snippet incluant "performance polos to classic polo shirts" + "Free Shipping With an RL Account & Free Returns" — USP claire
- **Southern Tide** : snippet positionnement lifestyle "effortless style and movement - on and off the golf course" — ciblage golf/outdoor

## Points clés
1. **Les 2 premiers résultats sont techniquement inaccessibles** (Akamai/scraping bloqué), ce qui limite l'analyse mais confirme que les gros retailers US protègent activement leur contenu
2. **Ralph Lauren est le seul vrai concurrent direct de Lacoste** sur cette SERP — les autres sont des marques niche (Southern Tide = preppy côtier, Musto = nautique, Tentree = éco). La fenêtre est grande ouverte pour Lacoste
3. L'absence totale de structured data dans le top 3 est une **opportunité de disruption technique** : Lacoste pourrait se différencier par un balisage Product + Offer supérieur dès son entrée sur le marché US polo shirt`,
  },
];

async function main() {
  console.log(`=== Inserting ${analyses.length} Claude Opus analyses ===`);
  console.log(`Run ID: ${RUN_ID}`);

  let inserted = 0;
  let skipped = 0;
  let errors = 0;

  for (const analysis of analyses) {
    // Check if analysis already exists
    const { data: existing } = await supabase
      .from('analyses')
      .select('id')
      .eq('run_id', analysis.run_id)
      .eq('keyword_id', analysis.keyword_id)
      .eq('country', analysis.country)
      .eq('device', analysis.device)
      .eq('analysis_type', analysis.analysis_type);

    if (existing && existing.length > 0) {
      console.log(`  SKIP: ${analysis.analysis_type} for ${analysis.keyword_id}/${analysis.country} already exists`);
      skipped++;
      continue;
    }

    const { error } = await supabase.from('analyses').insert(analysis);

    if (error) {
      console.error(`  ERROR: ${analysis.analysis_type} for ${analysis.keyword_id}/${analysis.country}: ${error.message}`);
      errors++;
    } else {
      console.log(`  OK: ${analysis.analysis_type} for kw=${analysis.keyword_id.slice(0, 8)}... / ${analysis.country}`);
      inserted++;
    }
  }

  console.log(`\n=== Done ===`);
  console.log(`Inserted: ${inserted}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Errors: ${errors}`);
}

main().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
